---
inherit_gem:
  rubocop-rickselby:
    - config/default.yml
    - config/rspec.yml
    - config/sequel.yml

# Allow constant definitions in the 'configure' block
Lint/ConstantDefinitionInBlock:
  AllowedMethods:
    - configure
